Make ghostscript more resilient to failure

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -24,18 +24,39 @@ export_env_dir() {
 export_env_dir $ENV_DIR
 
 GHOSTSCRIPT_VERSION="${GHOSTSCRIPT_VERSION:-9.53.3}"
-GHOSTSCRIPT_VERSION_NUMBERS_ONLY=${VERSION//[.]/}
-
+GHOSTSCRIPT_VERSION_NUMBERS_ONLY=${GHOSTSCRIPT_VERSION//[.]/}
 echo "-----> Installing Ghostscript $GHOSTSCRIPT_VERSION"
-PACKAGE="https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs$GHOSTSCRIPT_VERSION_NUMBERS_ONLY/ghostscript-$GHOSTSCRIPT_VERSION-linux-x86_64.tgz"
-BINARY="ghostscript-$GHOSTSCRIPT_VERSION-linux-x86_64/gs-$GHOSTSCRIPT_VERSION_NUMBERS_ONLY-linux-x86_64"
-LOCATION="$BUILD_DIR/vendor/gs/bin"
 
-mkdir -p $LOCATION
-curl $PACKAGE -s -L -o - | tar xzf - -C $LOCATION
-mv $LOCATION/$BINARY $LOCATION/gs
+VENDOR_DIR="$BUILD_DIR/vendor"
+INSTALL_DIR="$VENDOR_DIR/gs/bin"
+mkdir -p $INSTALL_DIR
+INSTALL_FILE="$INSTALL_DIR/gs"
+PACKAGE_DIR="ghostscript-$GHOSTSCRIPT_VERSION-linux-x86_64"
+PACKAGE_FILE="$PACKAGE_DIR.tgz"
+PACKAGE_URL="https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs$GHOSTSCRIPT_VERSION_NUMBERS_ONLY/$PACKAGE_FILE"
+CACHE_FILE="$CACHE_DIR/gs"
+DOWNLOADED_BIN_FILE="$VENDOR_DIR/$PACKAGE_DIR/gs-$GHOSTSCRIPT_VERSION_NUMBERS_ONLY-linux-x86_64"
 
-echo "-----> Building runtime environment for Ghostscript"
+if [ ! -f $CACHE_FILE ]; then
+  echo "-----> Downloading Ghostscript from $PACKAGE_URL"
+  wget $PACKAGE_URL -P $VENDOR_DIR | indent
 
+  if [ ! -f $VENDOR_DIR/$PACKAGE_FILE ]; then
+    echo "Error: Unable to download Ghostscript" | indent
+    ls $VENDOR_DIR | indent
+    exit 1;
+  fi
+
+  echo "-----> Extracting Ghostscript from $VENDOR_DIR/$PACKAGE_FILE"
+  tar xvf $VENDOR_DIR/$PACKAGE_FILE | indent
+
+  echo "-----> Caching Ghostscript installation"
+  mv $DOWNLOADED_BIN_FILE $CACHE_FILE
+fi
+
+echo "-----> Copying binaries"
+cp $CACHE_FILE $INSTALL_FILE
+
+echo "-----> Setting up profile for Ghostscript"
 mkdir -p $BUILD_DIR/.profile.d
 echo "export PATH=\"\$HOME/vendor/gs/bin:\$PATH\"" > $BUILD_DIR/.profile.d/ghostscript.sh
